name: Create Preview App

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
    deploy:
    if: "!contains(github.event.pull_request.title, 'SKIP REVIEW')"
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          scp -r . deploy@ec2-44-203-177-85.compute-1.amazonaws.com:~/app/${{ github.head_ref }}
      - name: Restarting App
        run: |
          ssh deploy@ec2-44-203-177-85.compute-1.amazonaws.com "cp ~/ecosystem.config.js ~/app/${{ github.head_ref }}/ && pushd ~/app/${{ github.head_ref }}  && npm install && pm2 restart ecosystem.config.js --name ${{ github.head_ref }} --env production --update-env && popd"
