name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint sourse code with ESLint
        run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    container: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint sourse code with ESLint
        run: npm run check:format
